name: 📦 Docker Snapshot Build and Push

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - 'CODEOWNERS'
      - '**.md'
      - '.**'

env:
  CURRENT_BRANCH: ${{ github.ref_name }}

permissions:
  packages: write
  contents: read

jobs:
  docker-build:
    name: 📦 Docker Build and Push
    runs-on: ubuntu-22.04
    steps:
      - name: 🔖 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ env.CURRENT_BRANCH }}

      - name: 🐳 Run Snapshot Docker Build/Push
        # https://github.com/pagopa/github-actions-template/releases/tag/v2.4.1
        uses: pagopa/github-actions-template/payments-flow-docker-snapshot@713f5abd8f8ee210e5f6a4243ae52eb7c1b3b5ab
        with:
          current_branch: ${{ env.CURRENT_BRANCH }}
